site_name: page labs
nav:
  - Home: index.md
  - About: about.md
  - Hardware:
    - Schematics: hardware/schematics.md
    - Layout: hardware/layout.md
  - Software:
    - HAL: hal.md
theme: readthedocs
# https://www.mkdocs.org/user-guide/writing-your-docs/